version: '3'
services:
  traefik:
    container_name: shareleaf_traefik
    restart: always
    image: traefik:v1.7
    command:
      --configFile=/var/traefik/traefik.toml
    labels:
      - traefik.frontend.rule=Host:monitor.shareleaf.co
      - traefik.docker.network=traefik_network
      - traefik.port=8080
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/var/traefik/traefik.toml:ro
      - /srv/docker/volumes/traefik/log:/log

networks:
  traefik_network:
    external: true