version: '3.8'
services:
  rr_test_postgres:
    image: postgres
    command: postgres -c 'max_connections=2000'
    container_name: rr_test_postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=repo
    ports:
      - "6432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
