version: "3.3"
services:
  shareleaf_ui:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/shareleaf:shareleaf-prod-ui-latest
    container_name: shareleaf-ui
    restart: always
    ports:
      - "3000:3000"